[book]
authors = ["Denis Merigoux"]
language = "en"
multilingual = false
src = "src"
title = "The Catala domain-specific programming language"

[preprocessor.curly-quotes]

[output.wordcount]
[output.html]
